[package]
name = "sun-orbit-simulation"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.17", features = ["dynamic_linking"] }

# fix load times for debug builds
[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
