[package]
name = "sun-orbit-simulation"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.17"

# fix load times for debug builds
[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3